# Vite + React application configuration for Netlify
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  # Disable framework auto-detection to prevent Next.js plugin
  NETLIFY_SKIP_FRAMEWORK_DETECTION = "true"

# Disable automatic framework detection since this is a Vite app, not Next.js
[build.processing]
  skip_processing = false


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["@google/generative-ai", "firebase-admin", "firebase"]
  node_bundler = "esbuild"